name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest
    name: Build and Test Web App
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./web
        run: npm ci
      
      - name: Install library dependencies
        working-directory: ./lib/org-social-parser-js
        run: npm ci
      
      - name: Lint project
        working-directory: ./web
        run: npm run lint
      
      - name: Build project
        working-directory: ./web
        run: npm run build
      
      - name: Run tests
        working-directory: ./web
        run: npm test

  lib:
    runs-on: ubuntu-latest
    name: Build and Test Library
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'lib/org-social-parser-js/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./lib/org-social-parser-js
        run: npm ci
      
      - name: Run tests
        working-directory: ./lib/org-social-parser-js
        run: npm test
